-- Chhajed Food Products — product catalog managed via /admin
-- Applied to Supabase project 500Kcal (tjrnymqmayqpdggtvhjr) on 2026-09-03.

create table if not exists public.cfp_products (
  id            bigint generated by default as identity primary key,
  name          text not null,
  brand         text not null default '',
  category      text not null default '',
  image         text not null default '/assets/images/no_image.png',
  alt           text not null default '',
  mrp           numeric not null default 0,
  selling_price numeric not null default 0,
  description   text not null default '',
  weight        text not null default '',
  prep_time     text not null default 'Ready to use',
  dietary       text[] not null default '{}',
  nutritional   jsonb not null default '{"calories":0,"protein":0,"carbs":0,"fat":0}'::jsonb,
  in_stock      boolean not null default true,
  featured      boolean not null default false,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists cfp_products_category_idx on public.cfp_products (category);
create index if not exists cfp_products_sort_idx on public.cfp_products (sort_order, id);

create or replace function public.cfp_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cfp_products_set_updated_at on public.cfp_products;
create trigger cfp_products_set_updated_at
  before update on public.cfp_products
  for each row execute function public.cfp_set_updated_at();

-- Catalog is world-readable; every write goes through the service role (admin API).
alter table public.cfp_products enable row level security;

drop policy if exists cfp_products_public_read on public.cfp_products;
create policy cfp_products_public_read
  on public.cfp_products for select using (true);

-- Public image bucket; uploads happen via the service role in /api/admin/upload.
insert into storage.buckets (id, name, public)
values ('cfp-product-images', 'cfp-product-images', true)
on conflict (id) do nothing;

-- Initial 56 rows were seeded from src/data/products.ts (see git history for that file).
